// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aurjxpvrwhvnzmtbduwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1cmp4cHZyd2h2bnptdGJkdXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MjAwOTksImV4cCI6MjA4Nzk5NjA5OX0.8cMQwJ8X-AJ0QGwOdH8Tuj_fv_J4Jn_FPWDwZCxrzrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});